from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, Float, String, Date, ForeignKey, Boolean

Base = declarative_base()
 
class RaceInfo(Base):
    __tablename__ = 'race_info'
 
    id = Column(Integer, primary_key=True)
    race_num = Column(Integer, ForeignKey("race_result.race_num"))
    year = Column(Integer)
    is_race_no_flying = Column(Boolean)
    is_race_times_record_valid = Column(Boolean)
    lane_length = Column(String)
    weather = Column(String)
    wind_direction = Column(String)
    wind_strength = Column(Integer)
    wave_height = Column(Integer) 
 
    #def __repr__(self):
    #    return "<Student(id='%s', name='%s', score='%s')>" % (self.id, self.name, self.score)
 
class RaceResult(Base):
    __tablename__ = 'race_result'
 
    id = Column(Integer, primary_key=True)
    race_num = Column(Integer)
    rank = Column(Integer)
    pitout_lane = Column(Integer)
    racer_id = Column(Integer)
    racer_name = Column(String(255))

    motor = Column(Integer)
    boat = Column(Integer)
    tenji = Column(Float)
    shinnyu = Column(Integer)
    start_timing = Column(Float)
    race_time = Column(Float)
    year = Column(Integer)
    date = Column(Date)
 
    #def __repr__(self):
    #    return "<Student(id='%s', name='%s', score='%s')>" % (self.id, self.name, self.score)


class RacerInfo(Base):
    __tablename__ = 'racer_info'

    id = Column(Integer, primary_key=True)
    racer_id = Column(Integer)
    racer_name_kanji = Column(String(255))
    racer_name_kana = Column(String(255))
    branch_prefecture = Column(String(10))
    racer_rank = Column(String(10))
    racer_rank_int = Column(Integer)
    birth_date = Column(Date)
    #1: male, 2:female
    racer_sex = Column(Integer)
    racer_age = Column(Integer)
    racer_height = Column(Integer)
    racer_weight = Column(Integer)
    racer_blood_type = Column(String(5))
    racer_win_rate = Column(Float)
    racer_double_win_rate = Column(Float)
    racer_first_arrival_times = Column(Integer)
    racer_second_arrival_times = Column(Integer)
    racer_start_times = Column(Integer)
    winner_race_start_times = Column(Integer)
    number_of_win = Column(Integer)
    average_start_timing = Column(Float)

    first_course_entry_time = Column(Integer)
    first_course_double_win_rate = Column(Float)
    first_course_average_start_timing = Column(Integer)
    first_course_average_start_rank = Column(Float)

    second_course_entry_time = Column(Integer)
    second_course_double_win_rate = Column(Float)
    second_course_average_start_timing = Column(Integer)
    second_course_average_start_rank = Column(Float)

    third_course_entry_time = Column(Integer)
    third_course_double_win_rate = Column(Float)
    third_course_average_start_timing = Column(Integer)
    third_course_average_start_rank = Column(Float)

    fourth_course_entry_time = Column(Integer)
    fourth_course_double_win_rate = Column(Float)
    fourth_course_average_start_timing = Column(Integer)
    fourth_course_average_start_rank = Column(Float)

    fifth_course_entry_time = Column(Integer)
    fifth_course_double_win_rate = Column(Float)
    fifth_course_average_start_timing = Column(Integer)
    fifth_course_average_start_rank = Column(Float)

    sixth_course_entry_time = Column(Integer)
    sixth_course_double_win_rate = Column(Float)
    sixth_course_average_start_timing = Column(Integer)
    sixth_course_average_start_rank = Column(Float)

    previous_period_rank = Column(String)
    previous_period_rank_int = Column(Integer)
    previous_second_period_rank = Column(String)
    previous_second_period_rank_int = Column(Integer)
    previous_third_period_rank = Column(String)
    previous_third_period_rank_int = Column(Integer)

    previous_period_capability_index = Column(Float)
    this_period_capability_index = Column(Float)

    year = Column(Integer)
    period = Column(Integer)
    calculation_period_begin = Column(Date)
    calculation_period_end = Column(Date)
    training_period = Column(Integer)

    first_course_first_arrive = Column(Integer)
    first_course_second_arrive = Column(Integer)
    first_course_third_arrive = Column(Integer)
    first_course_fourth_arrive = Column(Integer)
    first_course_fifth_arrive = Column(Integer)
    first_course_sixth_arrive = Column(Integer)
    first_course_f_times = Column(Integer)
    first_course_l0_times = Column(Integer)
    first_course_l1_times = Column(Integer)
    first_course_k0_times = Column(Integer)
    first_course_k1_times = Column(Integer)
    first_course_s0_times = Column(Integer)
    first_course_s1_times = Column(Integer)
    first_course_s2_times = Column(Integer)

    second_course_first_arrive = Column(Integer)
    second_course_second_arrive = Column(Integer)
    second_course_third_arrive = Column(Integer)
    second_course_fourth_arrive = Column(Integer)
    second_course_fifth_arrive = Column(Integer)
    second_course_sixth_arrive = Column(Integer)
    second_course_f_times = Column(Integer)
    second_course_l0_times = Column(Integer)
    second_course_l1_times = Column(Integer)
    second_course_k0_times = Column(Integer)
    second_course_k1_times = Column(Integer)
    second_course_s0_times = Column(Integer)
    second_course_s1_times = Column(Integer)
    second_course_s2_times = Column(Integer)

    third_course_first_arrive = Column(Integer)
    third_course_second_arrive = Column(Integer)
    third_course_third_arrive = Column(Integer)
    third_course_fourth_arrive = Column(Integer)
    third_course_fifth_arrive = Column(Integer)
    third_course_sixth_arrive = Column(Integer)
    third_course_f_times = Column(Integer)
    third_course_l0_times = Column(Integer)
    third_course_l1_times = Column(Integer)
    third_course_k0_times = Column(Integer)
    third_course_k1_times = Column(Integer)
    third_course_s0_times = Column(Integer)
    third_course_s1_times = Column(Integer)
    third_course_s2_times = Column(Integer)

    fourth_course_first_arrive = Column(Integer)
    fourth_course_second_arrive = Column(Integer)
    fourth_course_third_arrive = Column(Integer)
    fourth_course_fourth_arrive = Column(Integer)
    fourth_course_fifth_arrive = Column(Integer)
    fourth_course_sixth_arrive = Column(Integer)
    fourth_course_f_times = Column(Integer)
    fourth_course_l0_times = Column(Integer)
    fourth_course_l1_times = Column(Integer)
    fourth_course_k0_times = Column(Integer)
    fourth_course_k1_times = Column(Integer)
    fourth_course_s0_times = Column(Integer)
    fourth_course_s1_times = Column(Integer)
    fourth_course_s2_times = Column(Integer)

    fifth_course_first_arrive = Column(Integer)
    fifth_course_second_arrive = Column(Integer)
    fifth_course_third_arrive = Column(Integer)
    fifth_course_fourth_arrive = Column(Integer)
    fifth_course_fifth_arrive = Column(Integer)
    fifth_course_sixth_arrive = Column(Integer)
    fifth_course_f_times = Column(Integer)
    fifth_course_l0_times = Column(Integer)
    fifth_course_l1_times = Column(Integer)
    fifth_course_k0_times = Column(Integer)
    fifth_course_k1_times = Column(Integer)
    fifth_course_s0_times = Column(Integer)
    fifth_course_s1_times = Column(Integer)
    fifth_course_s2_times = Column(Integer)

    sixth_course_first_arrive = Column(Integer)
    sixth_course_second_arrive = Column(Integer)
    sixth_course_third_arrive = Column(Integer)
    sixth_course_fourth_arrive = Column(Integer)
    sixth_course_fifth_arrive = Column(Integer)
    sixth_course_sixth_arrive = Column(Integer)
    sixth_course_f_times = Column(Integer)
    sixth_course_l0_times = Column(Integer)
    sixth_course_l1_times = Column(Integer)
    sixth_course_k0_times = Column(Integer)
    sixth_course_k1_times = Column(Integer)
    sixth_course_s0_times = Column(Integer)
    sixth_course_s1_times = Column(Integer)
    sixth_course_s2_times = Column(Integer)

    no_course_l0_times = Column(Integer)
    no_course_l1_times = Column(Integer)
    no_course_k0_times = Column(Integer)
    no_course_k1_times = Column(Integer)

    birth_place = Column(String(10))
